### ISSUE TITLE
Add source code for AOT.exe here

### ISSUE THREAD

**Issue by Erlite** [vm-devr/aot#4]
Hi!

According to #3 you said you'd add the source code for AOT.exe to the repo. It seems like you haven't.

**Comment by Erlite** [comment]
So.... why didn't you do it? It takes 10 seconds to send the source code. If you know how to add releases to a repo and some config/html files, adding simple source code from a "file so small it can't be harmful" shouldn't be hard.

Sounds dodgy to me.

**Comment by vm-devr** [comment]
> So.... why didn't you do it? It takes 10 seconds to send the source code. If you know how to add releases to a repo and some config/html files, adding simple source code from a "file so small it can't be harmful" shouldn't be hard.
> 
> Sounds dodgy to me.

Hello Erlite,

Yes, it definitely sounds dodgy to me too. And, if you ask, I'd never have installed such a piece of code )
You also have to understand that I'm not making any money out of it.  The top reason I've implemented the addon in the first place is because I needed it myself.

Anyway, you are completely right - the code should be visible to all:
https://github.com/vm-devr/aot/blob/master/src.cpp
Now everyone can build it by himself and use his own host app.

Thank you,

Best regards,
Vasyl Maherka
